// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changedmodelvalidation2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedmodelvalidation2));
        
        string IMigrationMetadata.Id
        {
            get { return "201901071828425_Changed model validation 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
